import { SkillScreen } from '@/types/domain';
export const screens: SkillScreen[] = [
 {id:'splash',title:'Splash',category:'Authentication',description:'Brand-first launch with the SkillPilot AI mascot.',cta:'Get Started'},
 {id:'welcome',title:'Welcome',category:'Authentication',description:'Explain personalized roadmaps, feedback, and smart resources.',cta:'Next'},
 {id:'login',title:'Login',category:'Authentication',description:'Secure sign in with validation and token storage.',cta:'Login'},
 {id:'signup',title:'Signup',category:'Authentication',description:'Create an account and start a learning profile.',cta:'Create Account'},
 {id:'otp',title:'OTP',category:'Authentication',description:'Verify email or phone with a one-time passcode.',cta:'Verify'},
 {id:'forgot',title:'Forgot Password',category:'Authentication',description:'Recover access with a guided reset flow.',cta:'Send Link'},
 {id:'goals',title:'Goals',category:'Onboarding',description:'Capture learner outcomes for roadmap generation.',cta:'Continue'},
 {id:'interests',title:'Interests',category:'Onboarding',description:'Choose hobbies and skills to personalize content.',cta:'Next'},
 {id:'level',title:'Skill Level',category:'Onboarding',description:'Assess confidence from beginner through advanced.',cta:'Next'},
 {id:'time',title:'Time Commitment',category:'Onboarding',description:'Set realistic daily practice availability.',cta:'Next'},
 {id:'ai-personalization',title:'AI Personalization',category:'Onboarding',description:'AI interview tunes pace, examples, and learning style.',cta:'Build Roadmap'},
 {id:'dashboard',title:'Dashboard',category:'Home',description:'Today mission, streak, XP, and current journey.',cta:'Continue'},
 {id:'continue-learning',title:'Continue Learning',category:'Home',description:'Resume lessons and challenges from the last checkpoint.',cta:'Resume'},
 {id:'daily-tasks',title:'Daily Tasks',category:'Home',description:'Practice, watch, read, and challenge plan for the day.',cta:'Start Plan'},
 {id:'weekly-progress',title:'Weekly Progress',category:'Home',description:'Weekly insight cards with accuracy and completed lessons.',cta:'View Insights'},
 {id:'learning-path',title:'Learning Path',category:'Roadmap',description:'Adaptive path from first steps to mastery.',cta:'Open Path'},
 {id:'skill-tree',title:'Skill Tree',category:'Roadmap',description:'Visual graph of milestones and locked skills.',cta:'Explore'},
 {id:'course-detail',title:'Course Detail',category:'Roadmap',description:'Outcomes, resources, and lesson modules.',cta:'Start Lesson'},
 {id:'lesson',title:'Lesson',category:'Roadmap',description:'Video, reading, notes, and next actions in one flow.',cta:'Next'},
 {id:'ai-coach-chat',title:'AI Coach Chat',category:'AI',description:'Text coach answers, simplifies, quizzes, and practices.',cta:'Ask Coach'},
 {id:'skill-analysis',title:'Skill Analysis',category:'AI',description:'AI highlights strengths, gaps, and practice priorities.',cta:'Analyze'},
 {id:'career-suggestions',title:'Career Suggestions',category:'AI',description:'Translate new skills into relevant career paths.',cta:'Explore Careers'},
 {id:'ai-replace',title:'AI Replace Lesson',category:'AI',description:'Swap a confusing lesson for simpler, shorter, or alternate content.',cta:'Replace Lesson'},
 {id:'quiz',title:'Quiz',category:'Practice',description:'Fast knowledge checks with explanations.',cta:'Next Question'},
 {id:'coding-challenge',title:'Coding Challenge',category:'Practice',description:'Hands-on challenge workspace and hints.',cta:'Run Check'},
 {id:'flash-cards',title:'Flash Cards',category:'Practice',description:'Spaced repetition cards for key concepts.',cta:'Flip Card'},
 {id:'leaderboard',title:'Leaderboard',category:'Community',description:'Friendly ranking by XP, streak, and challenge wins.',cta:'View Friends'},
 {id:'friends',title:'Friends',category:'Community',description:'Follow learners and compare journeys.',cta:'Invite'},
 {id:'discussion',title:'Discussion',category:'Community',description:'Lesson-level discussions and peer help.',cta:'Join'},
 {id:'achievements',title:'Achievements',category:'Profile',description:'Badges for streaks, first chords, consistency, and exploration.',cta:'View All'},
 {id:'certificates',title:'Certificates',category:'Profile',description:'Shareable completion credentials.',cta:'Open'},
 {id:'analytics',title:'Analytics',category:'Profile',description:'Practice time, accuracy trends, and goal progress.',cta:'Review'},
 {id:'settings',title:'Settings',category:'Profile',description:'Notifications, reminders, privacy, and appearance.',cta:'Save'},
 {id:'profile',title:'Profile',category:'Profile',description:'Learner identity, XP, goals, notes, and resources.',cta:'Edit Profile'},
 {id:'subscription',title:'Subscription',category:'Profile',description:'Pro upgrade with unlimited coaching and advanced analytics.',cta:'Start Trial'},
 {id:'empty-state',title:'Empty State',category:'Home',description:'Friendly fallback when no lessons exist yet.',cta:'Create Journey'}
];
